#!/bin/bash
PIDW=
trap "echo \"Stoping warp...\"; warp-cli disconnect ;pkill -15 vpn-warp" 2
for ((;;)); do
   kill -15 $PIDW 1>/dev/null 2>/dev/null
   for ((;;)); do
      if [[ $(ifconfig | grep CloudflareWARP) = '' ]];then
         echo "Restoring connection to warp"
         /bin/warp-cli register && /bin/warp-cli connect
         date +"%H:%M"
         sleep 3
         curl 2ip.ua
      fi
      sleep 5 
   done &
   PIDW=$!
   if [[ $(ifconfig | grep CloudflareWARP) != '' ]];then
      echo ''
      /bin/warp-cli register && /bin/warp-cli connect
      date +"%H:%M"
      sleep 3
      curl 2ip.ua
   fi
   sleep $(($((RANDOM%15+15))*60))
done
wait
