# tasks file for pptp-linux
- name: Установка зависимостей
  apt: 
    name: 
      - pptp-linux
      - curl
    state: present
    update_cache: yes

- name: Отправка конфигов vpn
  copy:
    src: "{{ item }}"
    dest: /etc/ppp/peers/
    mode: 0644
  with_fileglob:
    - "vpn*"

- name: Отправка конфига chap
  copy:
    src: chap-secrets
    dest: /etc/ppp/
    mode: 0600

- name: Отправка скриптов IP
  copy:
    src: "{{ item }}"
    dest: /etc/ppp/
    mode: 0755
  with_fileglob:
    - "ip*"

- name: Получение архива db1000n
  get_url:
    url: https://github.com/arriven/db1000n/releases/download/v0.9.4/db1000n_linux_amd64.tar.gz
    dest: /root/
    mode: 0644

- name: Распаковка бинарника db1000n
  shell: "tar -xf /root/db1000n_linux_amd64.tar.gz -C /root/ && rm /root/db1000n_linux_amd64.tar.gz"
