---
# tasks file for pptp-linux-check
- name: Проверка состояния VPN подключения
  shell: "/usr/bin/curl 2ip.ua && /usr/sbin/ifconfig | /usr/bin/grep ppp0"
  register: res
  changed_when: false

- name: Отображние информации
  debug: msg="{{ res.stdout }}"