---
# tasks file for pptp-linux-check
- name: Проверка внешнего IP
  shell: "/usr/bin/curl 2ip.ua"
  register: res1
  changed_when: false

- name: Проверка номера VPN подключения
  shell: "/usr/bin/ps -aux | grep call"
  register: res2
  changed_when: false

- name: Отображние информации
  debug:
    msg: "{{ res1.stdout }} {{ res2.stdout }}"