---
# tasks file for pptp-linux-stop
- name: Стоп подключения pptp node1
  command: poff vpn"{{ item.vpnnum }}"
  when: inventory_hostname == 'node1'
  with_items: 
    - vpnnum: 3

- name: Стоп подключения pptp node2
  command: poff vpn"{{ item.vpnnum }}"
  when: inventory_hostname == 'node2'
  with_items: 
    - vpnnum: 4

- name: Стоп подключения pptp node3
  command: poff vpn"{{ item.vpnnum }}"
  when: inventory_hostname == 'node3'
  with_items: 
    - vpnnum: 5