# tasks file for pptp-linux
- name: Обновление кеша apt
  apt: 
    update_cache: yes

- name: Установка pptp-linux
  apt: 
    name: 
      - pptp-linux
      - curl
    state: present

- name: Отправка конфигов vpn
  copy:
    src: "{{ item }}"
    dest: /etc/ppp/peers/
    mode: 0644
  with_fileglob:
    - "vpn*"

- name: Отправка конфига chap
  copy:
    src: chap-secrets
    dest: /etc/ppp/
    mode: 0600

- name: Отправка скриптов IP
  copy:
    src: "{{ item }}"
    dest: /etc/ppp/
    mode: 0755
  with_fileglob:
    - "ip*"